### ISSUE TITLE
PurgeCSS impact on v-tooltip

### ISSUE THREAD

**Issue by amrap030** [Akryum/v-tooltip#552]
Hello together,

unfortunately if I am using PurgeCSS it messes up my Tooltips. There is no arrow anyomore and the Tooltip is visible for multiple seconds instead of disappearing when hovering away. Without PurgeCSS everything works fine. This is my PurgeCSS code:

```javascript
const purgecss = require("@fullhuman/postcss-purgecss")({
  // Specify the paths to all of the template files in your project
  content: [
    "./src/**/*.html",
    "./src/**/*.vue",
    "./src/**/*.jsx",
    "./src/App.vue",
    // etc.
  ],
  whitelist: [
    "tooltip",
    "tooltip-arrow",
    "tooltip-inner",
    "tooltip-sidebar",
    "vue-tooltip-theme",
    "tooltip[aria-hidden='true']",
    "tooltip[aria-hidden='false]",
    "tooltip[x-placement^='top']",
    "tooltip[x-placement^='right']",
  ],

  // This is the function used to extract class names from your templates
  defaultExtractor: (content) => {
    // Capture as liberally as possible, including things like `h-(screen-1.5)`
    const broadMatches = content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [];

    // Capture classes within other delimiters like .block(class="w-1/2") in Pug
    const innerMatches = content.match(/[^<>"'`\s.()]*[^<>"'`\s.():]/g) || [];

    return broadMatches.concat(innerMatches);
  },
});
```

in App.vue I have the following classes:

```css
.tooltip {
  display: block !important;
  z-index: 10000;
}

.tooltip .tooltip-inner {
  background: black;
  color: white;
  border-radius: 6px;
  padding: 8px 14px 8px;
  @apply text-xs font-semibold;
}

.tooltip .tooltip-arrow {
  width: 0;
  height: 0;
  border-style: solid;
  position: absolute;
  margin: 5px;
  border-color: black;
  z-index: 1;
}

.tooltip[x-placement^="top"] {
  margin-bottom: 2px;
}

.tooltip[x-placement^="top"] .tooltip-arrow {
  border-width: 6px 6px 0 6px;
  border-left-color: transparent !important;
  border-right-color: transparent !important;
  border-bottom-color: transparent !important;
  bottom: -6px;
  left: calc(50% - 5px);
  margin-top: 0;
  margin-bottom: 0;
}

.tooltip[x-placement^="right"] {
  margin-left: 5px;
}

.tooltip[x-placement^="right"] .tooltip-arrow {
  border-width: 5px 5px 5px 0;
  border-left-color: transparent !important;
  border-top-color: transparent !important;
  border-bottom-color: transparent !important;
  left: -5px;
  top: calc(50% - 5px);
  margin-left: 0;
  margin-right: 0;
}

.tooltip[aria-hidden="true"] {
  visibility: hidden;
  opacity: 0;
  transition: opacity 0.15s, visibility 0.15s;
}

.tooltip[aria-hidden="false"] {
  visibility: visible;
  opacity: 1;
  transition: opacity 0.15s;
}
```

**Comment by amrap030** [comment]
Got rid of it with:

```css
/* purgecss ignore */
.tooltip {
  display: block !important;
  z-index: 10000;
}

/* purgecss ignore */
.tooltip .tooltip-inner {
  background: black;
  color: white;
  border-radius: 6px;
  padding: 8px 14px 8px;
  @apply text-xs font-semibold;
}

/* purgecss ignore */
.tooltip .tooltip-arrow {
  width: 0;
  height: 0;
  border-style: solid;
  position: absolute;
  margin: 5px;
  border-color: black;
  z-index: 1;
}

/* purgecss ignore */
.tooltip[x-placement^="top"] {
  margin-bottom: 2px;
}

/* purgecss ignore */
.tooltip[x-placement^="top"] .tooltip-arrow {
  border-width: 6px 6px 0 6px;
  border-left-color: transparent !important;
  border-right-color: transparent !important;
  border-bottom-color: transparent !important;
  bottom: -6px;
  left: calc(50% - 5px);
  margin-top: 0;
  margin-bottom: 0;
}

/* purgecss ignore */
.tooltip[x-placement^="right"] {
  margin-left: 5px;
}

/* purgecss ignore */
.tooltip[x-placement^="right"] .tooltip-arrow {
  border-width: 5px 5px 5px 0;
  border-left-color: transparent !important;
  border-top-color: transparent !important;
  border-bottom-color: transparent !important;
  left: -5px;
  top: calc(50% - 5px);
  margin-left: 0;
  margin-right: 0;
}

/* purgecss ignore */
.tooltip[aria-hidden="true"] {
  visibility: hidden;
  opacity: 0;
  transition: opacity 0.15s, visibility 0.15s;
}

/* purgecss ignore */
.tooltip[aria-hidden="false"] {
  visibility: visible;
  opacity: 1;
  transition: opacity 0.15s;
}
```
